defaults:
  - level1_close_drawer
  - _self_

name: Level1_close_drawer_noise_v10

noise:
  enabled: true
  noise_scale: 1.0
  failure_bias_ratio: 0.0
  noise_distribution: "uniform"
  push_distance_distribution: "min_bias"
  drawer_approach_offset_x_distribution: "uniform"
  drawer_push_offset_x_distribution: "min_bias"
  drawer_contact_offset_y_distribution: "edge_bias"
  drawer_contact_offset_z_distribution: "edge_bias"
  end_effector_euler_distribution: "edge_bias"
  push_distance: [-0.105, -0.010]
  drawer_approach_offset_x: [-0.012, 0.004]
  drawer_push_offset_x: [-0.030, 0.000]
  drawer_contact_offset_y: [-0.085, 0.085]
  drawer_contact_offset_z: [-0.005, 0.060]
  end_effector_euler_deg: [-8.0, 8.0]
