name: Level1_shake

task_type: "shake"
controller_type: "shake"

mode: "collect"  # "collect" or "infer"

usd_path: "assets/chemistry_lab/lab_003/lab_003.usd"
obj_path: "/World/beaker_2"
sub_obj_path: "/World/beaker_2/mesh"

max_episodes: 100

infer:
  type: "local"
  obs_names: {"camera_1_rgb": 'camera_1_rgb', "camera_2_rgb": 'camera_2_rgb'}
  policy_model_path: ""
  policy_config_path: ""
  normalizer_path: ""
  host: "127.0.0.1"
  port: 8000
  n_obs_steps: 1
  timeout: 30
  max_retries: 3

task:
  camera_warmup_frames: 45
  max_steps: 3000
  obj_paths:
    - path: "/World/beaker_2"
      position_range:
        x: [0.19, 0.34]
        y: [-0.05, 0.05]
        z: [0.80, 0.80]

cameras:
  - prim_path: "/World/Camera1"
    name: "camera_1"
    translation: [2, 0, 2]
    resolution: [256, 256]
    focal_length: 4
    orientation: [0.61237, 0.35355, 0.35355, 0.61237]
    image_type: "rgb"

  - prim_path: "/World/Camera2"
    name: "camera_2"
    translation: [0.1, 0, 2.5]
    resolution: [256, 256]
    focal_length: 4
    orientation: [0.70711, 0, 0, -0.70711]
    image_type: "rgb"

  - prim_path: "/World/Franka/panda_hand/arm_camera"
    name: "camera_3"
    resolution: [256, 256]
    image_type: "rgb"

robot:
  type: "franka"
  position: [-0.4, -0, 0.71]

collector:
  type: "default"
  compression: gzip  
  save_frames: -1

shake:
  pick:
    events_dt: [0.003, 0.0015, 0.004, 0.01, 0.02, 0.003, 0.02]
    position_threshold: 0.005
    object_name: "beaker"
    gripper_distance: 0.02
    end_effector_euler_deg: [0.0, 90.0, 30.0]
    pre_offset_x: 0.05
    pre_offset_z: 0.05
    after_offset_z: 0.15
  motion:
    events_dt: [0.02, 0.018, 0.018, 0.018, 0.018, 0.018, 0.018, 0.018, 0.03, 0.03]
    end_effector_euler_deg: [0.0, 90.0, 10.0]
    shake_distance: 0.08
    initial_position_offset: [0.0, 0.0, 0.0]
  success:
    min_lift_height: 0.05
    min_shake_span_xy: 0.045
    required_shake_count: 5
    hold_steps: 60
    max_hold_xy_delta: 0.0125

hydra:
  run:
    dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}

multi_run:
  run_dir: outputs/${mode}/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}
