defaults:
  - level1_close_drawer
  - _self_

name: Level1_close_drawer_noise_v7

noise:
  enabled: true
  noise_scale: 1.15
  failure_bias_ratio: 0.85
  noise_distribution: "uniform"
  push_distance_distribution: "min_bias"
  drawer_approach_offset_x_distribution: "min_bias"
  drawer_push_offset_x_distribution: "min_bias"
  drawer_contact_offset_y_distribution: "edge_bias"
  drawer_contact_offset_z_distribution: "max_bias"
  end_effector_euler_distribution: "edge_bias"
  push_distance: [-0.110, -0.020]
  drawer_approach_offset_x: [-0.110, -0.040]
  drawer_push_offset_x: [-0.080, -0.020]
  drawer_contact_offset_y: [-0.180, 0.180]
  drawer_contact_offset_z: [0.040, 0.160]
  end_effector_euler_deg: [-12.0, 12.0]
